default: &default
  adapter: postgresql
  encoding: unicode
  database: city_taxi
  pool: 5
  username: city_taxi
  password: city_taxi

development:
  <<: *default

test:
  <<: *default
  database: city_taxi_test

production:
  <<: *default
  database: city_taxi_production
